// Stubs for path aliases used in the project to reduce TS errors during iteration.
declare module '$lib/*' {
  // Provide a few common named exports used across the frontend to reduce missing-export errors.
  export const convex: any;
  export const api: any;
  export const stores: any;
  export const utils: any;
  export const services: any;
  export default any;
}

// Convex generated types stub (will be generated by Convex codegen later)
declare module 'convex/_generated/*' {
  const anyExport: any;
  export = anyExport;
}

// Provide test globals used by Vitest/Jest mocks
declare const vi: any;

// Convex generated types stub (will be generated by Convex codegen later)
declare module 'convex/_generated/*' {
  const anyExport: any;
  export = anyExport;
}

// Provide test globals used by Vitest/Jest mocks
declare const vi: any;
