import { setupConvex } from "convex-svelte";

// Initialize Convex for Svelte using the public URL generated by `npx convex dev`.
const convexUrl = import.meta.env.PUBLIC_CONVEX_URL || import.meta.env.VITE_CONVEX_URL;
if (!convexUrl) {
  // Fallback: Convex dev server usually exposes a URL in .env.local; warn at runtime if missing.
  console.warn("PUBLIC_CONVEX_URL not found. Convex client may not be initialized.");
} else {
  setupConvex(convexUrl);
}