name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install -g pnpm@10.13.1
          pnpm --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Install app dependencies  
        working-directory: ./app
        run: |
          pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Build web app
        working-directory: ./app
        run: pnpm run build

      - name: Run convex codegen (typecheck disabled)
        working-directory: ./app
        run: npx convex codegen --typecheck=disable || true

      - name: Run lint (optional)
        working-directory: ./app
        run: pnpm run lint || true

      - name: Run unit tests
        working-directory: ./app
        run: pnpm run test || true
