name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install app dependencies
        working-directory: ./app
        run: npm install

      - name: Build web app
        working-directory: ./app
        run: npm run build

      - name: Run convex codegen (typecheck disabled)
        working-directory: ./app
        run: npx convex codegen --typecheck=disable || true

      - name: Run lint (optional)
        working-directory: ./app
        run: npm run lint || true

      - name: Run unit tests
        working-directory: ./app
        run: npm run test || true
