name: Spec-Kit Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Spec-Kit validation if script exists
        run: |
          if [ -f .github/spec-kit/validate.sh ]; then
            echo "Spec-Kit validation script found. Running..."
            bash .github/spec-kit/validate.sh
          else
            echo "Spec-Kit validation script not found. Skipping validation step." >&2
          fi
